### ISSUE TITLE
Implement Stochastic Shader (texture tiling correction)

### ISSUE THREAD

**Issue by Nekrodamus93** [papadanku/RealityShaders#1]
The solution is excellent and replaces nothing in your game , using a shader technique called “procedural stochastic texturing”.

![image](https://github.com/user-attachments/assets/da76fb9c-6f88-45c4-9a74-f7968daa5635)

The algorithm is based on a [paper by Thomas Deliot and Eric Heitz published in 2019](https://drive.google.com/file/d/1QecekuuyWgw68HU9tg6ENfrCTCVIjm6l/view) , both Unity Engine developers.

SOURCES:
https://www.mixmods.com.br/2022/03/shader-stochastic-gta-sa/
https://github.com/JuniorDjjr/skygfx
https://github.com/JuniorDjjr/Unity-Procedural-Stochastic-Texture-Terrain-Shader
https://github.com/JuniorDjjr/UnityProceduralStochasticTexturingNode

**Comment by papadanku** [comment]
We already have code for this sort of sampling in RealityShaders. However, it breaks when we have terrain tiles that are actually tiles. 😶‍🌫️

I think the workaround is some sort of interpolation between non-stochastic and stochastic
